

# Project configuration
data:
  raw_path: data/raw/survey.csv
  processed_path: data/processed/mental_health_cleaned.csv
  output_path: outputs/

models:
  logistic_regression: models/logistic_regression_model.pkl
  random_forest: models/random_forest_model.pkl
  xgboost: models/xgboost_model.pkl

train:
  test_size: 0.2
  random_state: 42

explainability:
  method: shap
  shap_summary: outputs/figures/shap_summary_xgb.png

dashboard:
  notebook_path: notebooks/dashboard.ipynb
  default_model: xgb_clf
